-- MySQL Script generated by MySQL Workbench
-- Fri Feb 19 09:02:11 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd_imob
-- -----------------------------------------------------
-- Banco de dados criado para o sistema imob com o uso da linguagem java
-- 
-- 
DROP SCHEMA IF EXISTS `bd_imob` ;

-- -----------------------------------------------------
-- Schema bd_imob
--
-- Banco de dados criado para o sistema imob com o uso da linguagem java
-- 
-- 
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_imob` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
SHOW WARNINGS;
USE `bd_imob` ;

-- -----------------------------------------------------
-- Table `tb_cidades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_cidades` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tb_cidades` (
  `idCidade` INT NOT NULL AUTO_INCREMENT,
  `nome_Cidade` VARCHAR(45) NULL,
  `tb_estados_id_estados` INT NOT NULL,
  PRIMARY KEY (`idCidade`, `tb_estados_id_estados`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tb_cliente_pessoa_juridica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_cliente_pessoa_juridica` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tb_cliente_pessoa_juridica` (
  `id_clientePJ` INT NOT NULL AUTO_INCREMENT,
  `id_codigo_pessoaPJ` INT NULL,
  `status_comprador` VARCHAR(45) NULL,
  `status_vendedor` VARCHAR(45) NULL,
  `status_locador` VARCHAR(45) NULL,
  `status_locatario` VARCHAR(45) NULL,
  `td_pessoa_juridica_idPessoaPJ` INT NOT NULL,
  `td_pessoa_juridica_tb_pessoa_id_pessoa` INT NOT NULL,
  PRIMARY KEY (`id_clientePJ`, `td_pessoa_juridica_idPessoaPJ`, `td_pessoa_juridica_tb_pessoa_id_pessoa`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tb_estados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_estados` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tb_estados` (
  `id_estados` INT NOT NULL AUTO_INCREMENT,
  `nome_Estado` VARCHAR(45) NULL,
  PRIMARY KEY (`id_estados`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tb_imobiliaria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_imobiliaria` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tb_imobiliaria` (
  `id_Imobliliaria` INT NOT NULL AUTO_INCREMENT,
  `id_Codigo_Imobiliaria` INT NULL,
  `numero_Creci` INT NULL,
  `td_pessoa_juridica_idPessoaPJ` INT NOT NULL,
  `td_pessoa_juridica_tb_pessoa_id_pessoa` INT NOT NULL,
  PRIMARY KEY (`id_Imobliliaria`, `td_pessoa_juridica_idPessoaPJ`, `td_pessoa_juridica_tb_pessoa_id_pessoa`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tb_loguin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_loguin` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tb_loguin` (
  `id_Login` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  `permissao` VARCHAR(45) NULL,
  `data_login` DATE NULL,
  `time_login` VARCHAR(45) NULL,
  `td_pessoa_fissica_id_clientePF` INT NOT NULL,
  `td_pessoa_fissica_tb_pessoa_id_pessoa` INT NOT NULL,
  PRIMARY KEY (`id_Login`, `td_pessoa_fissica_id_clientePF`, `td_pessoa_fissica_tb_pessoa_id_pessoa`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tb_pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_pessoa` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tb_pessoa` (
  `id_pessoa` INT NOT NULL AUTO_INCREMENT,
  `id_Codigo_Pessoa` INT NULL,
  PRIMARY KEY (`id_pessoa`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tb_prestadores_servico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_prestadores_servico` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tb_prestadores_servico` (
  `id_Prestador` INT NOT NULL AUTO_INCREMENT,
  `id_Codigo_Prestador` INT NULL,
  `id_Codigo_Servico` INT NULL,
  `tipo_Servico_Prestado` INT NULL,
  `data_Inicial` DATE NULL,
  `data_Final` DATE NULL,
  `anotacoes` VARCHAR(45) NULL,
  `td_pessoa_juridica_idPessoaPJ` INT NOT NULL,
  `td_pessoa_juridica_tb_pessoa_id_pessoa` INT NOT NULL,
  PRIMARY KEY (`id_Prestador`, `td_pessoa_juridica_idPessoaPJ`, `td_pessoa_juridica_tb_pessoa_id_pessoa`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `td_cartao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `td_cartao` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `td_cartao` (
  `id_Cartao` INT NOT NULL AUTO_INCREMENT,
  `id_Codigo_Cartao` INT NULL,
  `id_cliente` INT NULL,
  `numero_cartao` VARCHAR(45) NULL,
  `data_Vencimento` DATE NULL,
  `valor_Recebido` DOUBLE NULL,
  `tipo_cartao` VARCHAR(45) NULL,
  `anotacoes` VARCHAR(45) NULL,
  `bandeira_cartao` VARCHAR(45) NULL,
  `td_pagamentos_id_Pagamentos` INT NOT NULL,
  `td_pagamentos_tb_imobiliaria_id_Imobliliaria` INT NOT NULL,
  `td_pessoa_juridica_idPessoaPJ` INT NOT NULL,
  `tb_pessoa_id_pessoa` INT NOT NULL,
  PRIMARY KEY (`id_Cartao`, `td_pagamentos_id_Pagamentos`, `td_pagamentos_tb_imobiliaria_id_Imobliliaria`, `td_pessoa_juridica_idPessoaPJ`, `tb_pessoa_id_pessoa`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `td_cliente_pessoa_fissica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `td_cliente_pessoa_fissica` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `td_cliente_pessoa_fissica` (
  `id_clientePF` INT NOT NULL AUTO_INCREMENT,
  `id_codigo_clientePF` INT NULL,
  `status_comprador` VARCHAR(45) NULL,
  `status_vendedor` VARCHAR(45) NULL,
  `status_locador` VARCHAR(45) NULL,
  `status_locatario` VARCHAR(45) NULL,
  `td_pessoa_fissica_id_clientePF` INT NOT NULL,
  `td_pessoa_fissica_tb_pessoa_id_pessoa` INT NOT NULL,
  PRIMARY KEY (`id_clientePF`, `td_pessoa_fissica_id_clientePF`, `td_pessoa_fissica_tb_pessoa_id_pessoa`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `td_corretor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `td_corretor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `td_corretor` (
  `id_Corretor` INT NOT NULL AUTO_INCREMENT,
  `id_Codigo_Corretor` INT NULL,
  `numero_Creci` INT NULL,
  `td_pessoa_fissica_id_clientePF` INT NOT NULL,
  `td_pessoa_fissica_tb_pessoa_id_pessoa` INT NOT NULL,
  `td_pagamentos_id_Pagamentos` INT NOT NULL,
  `td_pagamentos_tb_imobiliaria_id_Imobliliaria` INT NOT NULL,
  `td_pagamentos_td_pessoa_juridica_idPessoaPJ` INT NOT NULL,
  `td_pagamentos_tb_pessoa_id_pessoa` INT NOT NULL,
  PRIMARY KEY (`id_Corretor`, `td_pessoa_fissica_id_clientePF`, `td_pessoa_fissica_tb_pessoa_id_pessoa`, `td_pagamentos_id_Pagamentos`, `td_pagamentos_tb_imobiliaria_id_Imobliliaria`, `td_pagamentos_td_pessoa_juridica_idPessoaPJ`, `td_pagamentos_tb_pessoa_id_pessoa`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `td_deposito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `td_deposito` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `td_deposito` (
  `id_Deposito` INT NOT NULL AUTO_INCREMENT,
  `id_Codigo_Deposito` INT NULL,
  `id_cliente` INT NULL,
  `data_Deposito` DATE NULL,
  `codigo_Identificacao` VARCHAR(45) NULL,
  `tipo_Deposito` VARCHAR(45) NULL,
  `anotacoes` VARCHAR(45) NULL,
  `confirmacao_deposito` VARCHAR(45) NULL,
  `deposito_realizado` VARCHAR(45) NULL,
  `td_pagamentos_id_Pagamentos` INT NOT NULL,
  `td_pagamentos_tb_imobiliaria_id_Imobliliaria` INT NOT NULL,
  `td_pagamentos_pessoa_juridica_idPessoaPJ` INT NOT NULL,
  `td_pagamentos_pessoa_id_pessoa` INT NOT NULL,
  PRIMARY KEY (`id_Deposito`, `td_pagamentos_id_Pagamentos`, `td_pagamentos_tb_imobiliaria_id_Imobliliaria`, `td_pagamentos_pessoa_juridica_idPessoaPJ`, `td_pagamentos_pessoa_id_pessoa`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `td_emails`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `td_emails` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `td_emails` (
  `id_Email` INT NOT NULL AUTO_INCREMENT,
  `id_Codigo_Email` INT NULL,
  `tipo_email` VARCHAR(100) NULL,
  `email` VARCHAR(45) NULL,
  `tb_pessoa_id_pessoa` INT NOT NULL,
  PRIMARY KEY (`id_Email`, `tb_pessoa_id_pessoa`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `td_endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `td_endereco` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `td_endereco` (
  `idtd_endereco` INT NOT NULL AUTO_INCREMENT,
  `tipo_Logradouro` VARCHAR(45) NULL,
  `logradouro` VARCHAR(45) NULL,
  `numero_Logradouro` VARCHAR(45) NULL,
  `complemento` VARCHAR(45) NULL,
  `cep` VARCHAR(45) NULL,
  `latitude` INT NULL,
  `longitude` INT NULL,
  `tb_cidades_idCidade` INT NOT NULL,
  `tb_cidades_tb_estados_id_estados` INT NOT NULL,
  `tb_pessoa_id_pessoa` INT NOT NULL,
  PRIMARY KEY (`idtd_endereco`, `tb_cidades_idCidade`, `tb_cidades_tb_estados_id_estados`, `tb_pessoa_id_pessoa`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `td_imovel_geral`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `td_imovel_geral` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `td_imovel_geral` (
  `id_imovel` INT NOT NULL AUTO_INCREMENT,
  `id_Codigo_Imovel` INT NULL,
  `status_venda` VARCHAR(45) NULL,
  `status_locacao` VARCHAR(45) NULL,
  `numero_Matricula` VARCHAR(45) NULL,
  `tipo_imovel` VARCHAR(45) NULL,
  `fotos` VARCHAR(45) NULL,
  `anotacoes` VARCHAR(45) NULL,
  `qualidade_Localizacao` VARCHAR(45) NULL,
  `qualidade_De_Acesso` VARCHAR(45) NULL,
  `td_endereco_idtd_endereco` INT NOT NULL,
  `td_endereco_tb_cidades_idCidade` INT NOT NULL,
  `td_endereco_tb_cidades_tb_estados_id_estados` INT NOT NULL,
  `td_endereco_tb_pessoa_id_pessoa` INT NOT NULL,
  PRIMARY KEY (`id_imovel`, `td_endereco_idtd_endereco`, `td_endereco_tb_cidades_idCidade`, `td_endereco_tb_cidades_tb_estados_id_estados`, `td_endereco_tb_pessoa_id_pessoa`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `td_imovel_rural`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `td_imovel_rural` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `td_imovel_rural` (
  `id_imovel_R` INT NOT NULL AUTO_INCREMENT,
  `numero_Itr` VARCHAR(45) NULL,
  `area_Total` INT NULL,
  `unidade_Area_Imovel` INT NULL,
  `area_app` INT NULL,
  `area_Utilizavel` INT NULL,
  `tem_curral` VARCHAR(45) NULL,
  `tem_casa_sede` VARCHAR(45) NULL,
  `	private String tem_casa_funcionarios;` VARCHAR(45) NULL,
  `tem_represa` VARCHAR(45) NULL,
  `tem_poco_artesiano` VARCHAR(45) NULL,
  `tem_rio` VARCHAR(45) NULL,
  `td_imovel_geral_id_imovel` INT NOT NULL,
  PRIMARY KEY (`id_imovel_R`, `td_imovel_geral_id_imovel`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `td_imovel_urbano`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `td_imovel_urbano` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `td_imovel_urbano` (
  `id_Imovel_U` INT NOT NULL AUTO_INCREMENT,
  `numero_Iptu` VARCHAR(45) NULL,
  `td_imovel_urbanocol` INT NULL,
  `area_Total` INT NULL,
  `area_Construida` INT NULL,
  `quant_banheiros` INT NULL,
  `quant_dormitorios` INT NULL,
  `quant_sala` INT NULL,
  `quant_suite` INT NULL,
  `quant_garagem_carro` INT NULL,
  `tem_garagem` VARCHAR(45) NULL,
  `tem_edicula` VARCHAR(45) NULL,
  `tem_churrasquira` VARCHAR(45) NULL,
  `td_imovel_geral_id_imovel` INT NOT NULL,
  PRIMARY KEY (`id_Imovel_U`, `td_imovel_geral_id_imovel`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `td_pagamentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `td_pagamentos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `td_pagamentos` (
  `id_Pagamentos` INT NOT NULL AUTO_INCREMENT,
  `id_Codigo_Pagamento` INT NULL,
  `data_Pagamento` DATE NULL,
  `data_Vencimento_Pagamento` DATE NULL,
  `juros_Mensais` DOUBLE NULL,
  `juros_Multas` DOUBLE NULL,
  `id_Codigo_Cliente` INT NULL,
  `forma_Pagamento` VARCHAR(45) NULL,
  `valor_Pagamento` DOUBLE NULL,
  `valor_desconto` DOUBLE NULL,
  `valor_Total_Pagamento` DOUBLE NULL,
  `numero_documento_Pagamento` INT NULL,
  `id_cliente` INT NULL,
  `id_imovel` INT NULL,
  `tb_imobiliaria_id_Imobliliaria` INT NOT NULL,
  `tb_imobiliaria_td_pessoa_juridica_idPessoaPJ` INT NOT NULL,
  `tb_imobiliaria_td_pessoa_juridica_tb_pessoa_id_pessoa` INT NOT NULL,
  PRIMARY KEY (`id_Pagamentos`, `tb_imobiliaria_id_Imobliliaria`, `tb_imobiliaria_td_pessoa_juridica_idPessoaPJ`, `tb_imobiliaria_td_pessoa_juridica_tb_pessoa_id_pessoa`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `td_pesquisa-cadastral`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `td_pesquisa-cadastral` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `td_pesquisa-cadastral` (
  `id_Pesquisa` INT NOT NULL AUTO_INCREMENT,
  `id_Codigo_Pesquisa_Cadastral` INT NULL,
  `codigo_Cliente` INT NULL,
  `data_Pesquisa` DATE NULL,
  `situacao_Pesquisa` LONGTEXT NULL,
  `data_proxima_pesquisa` DATE NULL,
  `tb_pessoa_id_pessoa` INT NOT NULL,
  PRIMARY KEY (`id_Pesquisa`, `tb_pessoa_id_pessoa`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `td_pessoa_fissica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `td_pessoa_fissica` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `td_pessoa_fissica` (
  `id_clientePF` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  `sobrenome` VARCHAR(100) NULL,
  `cpf` VARCHAR(45) NULL,
  `rg` VARCHAR(45) NULL,
  `date_nascimento` DATE NULL,
  `sexo` VARCHAR(45) NULL,
  `estado_Civil` VARCHAR(45) NULL,
  `regime_Bens` VARCHAR(45) NULL,
  `naturalidade` VARCHAR(45) NULL,
  `estado_naturalidade` VARCHAR(45) NULL,
  `escolaridade` VARCHAR(45) NULL,
  `profissao` VARCHAR(45) NULL,
  `anotacoes` VARCHAR(45) NULL,
  `nome_Pai` VARCHAR(100) NULL,
  `nome_mae` VARCHAR(100) NULL,
  `status_cadastro` VARCHAR(45) NULL,
  `tb_pessoa_id_pessoa` INT NOT NULL,
  PRIMARY KEY (`id_clientePF`, `tb_pessoa_id_pessoa`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `td_pessoa_juridica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `td_pessoa_juridica` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `td_pessoa_juridica` (
  `idPessoaPJ` INT NOT NULL AUTO_INCREMENT,
  `razao_Social` VARCHAR(45) NULL,
  `nome_Fantasma` VARCHAR(45) NULL,
  `cnpj` VARCHAR(45) NULL,
  `inscriçao_Estadual` VARCHAR(45) NULL,
  `isento_inscricao_E` VARCHAR(45) NULL,
  `atividades_Principais` VARCHAR(45) NULL,
  `atividades_Secundarias` VARCHAR(45) NULL,
  `data_servico` DATE NULL,
  `anotacoes` VARCHAR(45) NULL,
  `status_cadastro` VARCHAR(45) NULL,
  `tb_pessoa_id_pessoa` INT NOT NULL,
  PRIMARY KEY (`idPessoaPJ`, `tb_pessoa_id_pessoa`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `td_telefone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `td_telefone` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `td_telefone` (
  `id_telefone` INT NOT NULL AUTO_INCREMENT,
  `id_Codigo_Telefone` INT NULL,
  `tipo_telefone` VARCHAR(45) NULL,
  `numero_telefone` VARCHAR(45) NULL,
  `tb_pessoa_id_pessoa` INT NOT NULL,
  PRIMARY KEY (`id_telefone`, `tb_pessoa_id_pessoa`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
